title: Yuezihan Jiang Homepage
page-top-title: Yuezihan Jiang Homepage
# top-section-bg-text: A Dedicated NLP & MLSystem Nerd Dreaming of AGI World
home-subtitle: Yuezihan Jiang
copyright-text: '&copy; Yuezihan Jiang 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
